name: LinkedIn Scraper

# Déclencheurs (Triggers)
on:
  schedule:
    - cron: '0 8 * * *' # every day at 08:00 UTC (minute heure jour mois jour_semaine)
  workflow_dispatch: # allows manual run


jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      # Étape 1- Récupérer le code (Clone le dépôt GitHub): 
      - name: Checkout repository
        uses: actions/checkout@v3
      # Étape 2- Configurer Python:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      # Étape 3 : Installer les dépendances:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm
      # Étape 4 : Exécuter le scraper
      - name: Run scraper
        run: |
          python scraping/auto_scraper_linkedin.py
      # Étape 5 : Commit et push des données
      - name: Commit and push updated dataset
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/dataset_final.csv
          git commit -m "Update dataset_final.csv [Automated]" || echo "No changes to commit"
          git push
